name: Python Code Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-security:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получение кода
      - uses: actions/checkout@v4
      
      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 bandit
      
      # Шаг 4: Проверка форматирования Black
      - name: Check with Black
        run: black --check .
      
      # Шаг 5: Проверка стиля Flake8
      - name: Check with Flake8
        run: flake8 .
      
      # Шаг 6: НОВЫЙ ШАГ - Проверка безопасности Bandit
      - name: Check with Bandit
        run: |
          bandit -r . -ll  # Базовая проверка
          # Или с более строгими настройками:
          # bandit -r . --severity-level high --confidence-level high
